feat(01-building-blocks) added workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,9 +11,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps: 
-      - name: successful step
+      - name: failed step
         run: |
-         echo "i will succeed"
-         exit 0
+         echo "i will fail"
+         exit 1
       - name: say goodbye
         run: echo "goodbye!"
